### ISSUE TITLE
Implement a builder

### ISSUE THREAD

**Issue by szymonstuszek** [m-drzewko/WFRP2_NPC_generator_API#14]
Implement a builder pattern for classes that have a lot of fields, for example the Race related ones.

Hint: lombok provides an annotation for this, but it will not hurt to make a builder on your own

Some example links:
- https://www.digitalocean.com/community/tutorials/builder-design-pattern-in-java
- https://blogs.oracle.com/javamagazine/post/exploring-joshua-blochs-builder-design-pattern-in-java
- https://refactoring.guru/design-patterns -> great resource about design pattern

**Comment by m-drzewko** [comment]
Builder implemented as part of #32
