### ISSUE TITLE
Setup internationalization [api]

### ISSUE THREAD

**Issue by szymonstuszek** [m-drzewko/WFRP2_NPC_generator_API#20]
Placeholder

**Comment by m-drzewko** [comment]
It's possible some of the functionality required by internationalization on the backend will be done in #23, as it will require remodelling of Race and RaceStats entities

**Comment by m-drzewko** [comment]
Elements of this issue will be implemented across different other issues, where relevant. There will not be any singular localisation strategy on the backend, as this is mostly handled on the frontend, making extensive backend implementation redundant.
